---
- name: Déploiement complet de GLPI
  hosts: glpi
  become: true

  vars_files:
    - vars.yml

  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
    - role: geerlingguy.php
    - role: glpi
